version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=my_database

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8090:8080"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
